// Generates src/styles/_icons.scss from @fortawesome/fontawesome-free: every
// icon as a CSS mask, inked through currentColor. Scans src/ and
// maverick-wave.min.js for fa-* classes, so re-run after a framework upgrade.
//
//   node tools/icons.mjs
import { readdir, readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url).pathname;
const fa = `${root}node_modules/@fortawesome/fontawesome-free`;
const framework = `${root}node_modules/maverick-wave/maverick-wave.min.js`;
const target = `${root}src/styles/_icons.scss`;

// Order is precedence: a name in several styles is taken as solid.
const STYLES = ['solid', 'brands', 'regular'];

// Same namespace, but sizing/rotation/animation modifiers, not icon names.
const MODIFIERS =
  /^fa-(\d+x|2xs|xs|sm|lg|xl|2xl|fw|spin|spin-pulse|spin-reverse|pulse|beat|beat-fade|fade|bounce|shake|border|inverse|li|ul|stack|stack-1x|stack-2x|pull-left|pull-right|rotate-\w+|flip|flip-\w+|solid|regular|brands|light|thin|duotone|sharp|sharp-\w+)$/;

const filesUnder = async directory => {
  const entries = await readdir(directory, {
    recursive: true,
    withFileTypes: true,
  });
  return (
    entries
      .filter(e => e.isFile() && /\.(astro|ts|js|scss)$/.test(e.name))
      .map(e => `${e.parentPath}/${e.name}`)
      // Skip the generated file - it names every icon and would keep
      // unused ones alive forever.
      .filter(f => f !== target)
  );
};

const usedNames = async () => {
  const sources = [...(await filesUnder(`${root}src`)), framework];
  const names = new Set();
  for (const file of sources) {
    const content = await readFile(file, 'utf8');
    for (const [name] of content.matchAll(/\bfa-[a-z0-9]+(?:-[a-z0-9]+)*\b/g)) {
      if (!MODIFIERS.test(name)) names.add(name);
    }
  }
  return [...names].sort();
};

// Renamed icons (fa-home -> fa-house) only ship under the new name.
const aliasMap = async () => {
  const raw = await readFile(`${fa}/metadata/icon-families.json`, 'utf8');
  const map = new Map();
  for (const [canonical, entry] of Object.entries(JSON.parse(raw))) {
    for (const alias of entry.aliases?.names ?? []) map.set(alias, canonical);
  }
  return map;
};

const readSvg = async (name, alias) => {
  for (const candidate of [name, alias].filter(Boolean)) {
    for (const style of STYLES) {
      try {
        return await readFile(`${fa}/svgs/${style}/${candidate}.svg`, 'utf8');
      } catch {
        // try the next style
      }
    }
  }
  return null;
};

// A mask only uses the alpha, so colour and licence comment are dropped.
const dataUri = svg =>
  `url("data:image/svg+xml,${svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/%/g, '%25')
    .replace(/"/g, "'")
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/#/g, '%23')}")`;

const aliases = await aliasMap();
const icons = [];
const missing = [];

for (const className of await usedNames()) {
  const name = className.slice('fa-'.length);
  const svg = await readSvg(name, aliases.get(name));
  if (!svg) {
    missing.push(className);
    continue;
  }
  const [, width] = svg.match(/viewBox="0 0 (\d+) \d+"/);
  icons.push({ className, uri: dataUri(svg), width: Number(width) });
}

const version = JSON.parse(
  await readFile(`${fa}/package.json`, 'utf8')
).version;

// Font Awesome draws on an em square of 512; a wider glyph has a wider viewBox.
const rule = ({ className, uri, width }) =>
  [
    `.${className} {`,
    '  @extend %m1-icon;',
    `  --m1-icon: ${uri};`,
    width === 512 ? null : `  width: ${width / 512}em;`,
    '}',
  ]
    .filter(Boolean)
    .join('\n');

const stylesheet = `// GENERATED by tools/icons.mjs - do not edit, re-run the tool.
// Font Awesome Free ${version} icons (CC BY 4.0, https://fontawesome.com/license/free)
%m1-icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--m1-icon) center / contain no-repeat;
  mask: var(--m1-icon) center / contain no-repeat;
}

${icons.map(rule).join('\n\n')}
`;

await writeFile(target, stylesheet);

console.log(
  `${icons.length} icons -> src/styles/_icons.scss (${stylesheet.length} bytes)`
);
for (const { className, width } of icons) {
  console.log(`  ${className} (${width}/512)`);
}
if (missing.length) console.warn(`not found: ${missing.join(', ')}`);
